# Generated by Django 5.1 on 2024-09-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_auto_20220326_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
